### ISSUE TITLE
Fairyfloss for JetBrains Editor

### ISSUE THREAD

**Issue by ghost** [nopjmp/vscode-fairyfloss#1]
Hello, have you ever thought about doing a FairyFlos Theme for JetBrains editors?
Would be awesome!

**Comment by nopjmp** [comment]
I've thought about it. I kind of got used to stuff that's darker like Calamity

https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/screenshots/calamity.png

https://github.com/Pustur/calamity-vscode
